/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

/**
 * The list users results
 */
export interface UserList {
    /** List of Users for a Site */
    users?: Webflow.User[];
    pagination?: Webflow.Pagination;
}
