/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { User } from "./User";
import { Pagination } from "./Pagination";

export const UserList: core.serialization.ObjectSchema<serializers.UserList.Raw, Webflow.UserList> =
    core.serialization.object({
        users: core.serialization.list(User).optional(),
        pagination: Pagination.optional(),
    });

export declare namespace UserList {
    interface Raw {
        users?: User.Raw[] | null;
        pagination?: Pagination.Raw | null;
    }
}
